### PR TITLE
Test benchmarks in CI

### PR DESCRIPTION
**Pull request by cptartur**
Closes #

## Introduced changes

- Added a CI step that runs benchmarks using `cargo run --benches` command. This will run each benchmark only once, verifying that it passes, without time measurements etc.

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Review by Arcticae — COMMENTED** [review]
@cptartur does this have to be run on every commit? Wouldn't like a on-merge to main work better in this case, since this is not something that we necessarily need each time for the app to be releasable?

**Comment by Arcticae** [comment]
> Though if we don't add this step as required to the master branch protection I think merging PRs with benchmarks broken would still be possible. And we'll immediately know that a PR broke the benchmarks.

Yes, but we'll be taking up 6m of the time possibly blocking the merging while it's not necessary to block the PR because of that. And we'll still know after merging which one broke it

**Comment by cptartur** [comment]
> > Though if we don't add this step as required to the master branch protection I think merging PRs with benchmarks broken would still be possible. And we'll immediately know that a PR broke the benchmarks.
> 
> Yes, but we'll be taking up 6m of the time possibly blocking the merging while it's not necessary to block the PR because of that. And we'll still know after merging which one broke it



> > Though if we don't add this step as required to the master branch protection I think merging PRs with benchmarks broken would still be possible. And we'll immediately know that a PR broke the benchmarks.
> 
> Yes, but we'll be taking up 6m of the time possibly blocking the merging while it's not necessary to block the PR because of that. And we'll still know after merging which one broke it

Updated. Benchmarks tests will now only trigger on push (to master since it's the only push type that causes CI workflow to trigger).

**Review by Arcticae — CHANGES_REQUESTED** [review]
@cptartur i know this is easier but i would just run it with a different workflow, i don't need to know that it was skipped each time under a PR...

**Review by Arcticae — APPROVED** [review]

**Pull request merged**
