### PR TITLE
Extract integration helpers to separate package

### LINKED ISSUE #911: Extract integration tests helpers to separate package
Required for #682

### PR DESCRIPTION
**Pull request by cptartur**
Closes #911 

## Introduced changes

- Moved helper code from integration tests to `utils` crate within `forge` so it can be reused for benchmarks.

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Comment by piotmag769** [comment]
Don't merge it until my refactors are merged, please

**Review by piotmag769 — APPROVED** [review]
Feel free to merge after #919 is merged. 
Isn't `testing_utils` a better name though?

**Review by MaksymilianDemitraszek — COMMENTED** [review]
test_utils definitely would be  a better name

**Comment by cptartur** [comment]
No strong opinion on that, we can can it `test_utils`.

**Pull request merged**
