### PR TITLE
fix cheatnet fork cache

### PR DESCRIPTION
**Pull request by jainkunal**
## Introduced changes

-
-

## Checklist

- [ ] Linked relevant issue
- [ ] Updated relevant documentation
- [ ] Added relevant tests
- [x] Performed self-review of the code
- [ ] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Review by Arcticae — APPROVED** [review]

**Comment by Arcticae** [comment]
@jainkunal can you take a look at the failed tests, or should we do that instead?

**Comment by jainkunal** [comment]
I will give it a try, most of the tests didn't pass for me locally even without the change so I assumed it was unrelated. I will see what I can fix.

**Comment by drknzz** [comment]
> I will give it a try, most of the tests didn't pass for me locally even without the change so I assumed it was unrelated. I will see what I can fix.

Hey @jainkunal, could you give some more insight on what were the errors when you ran tests locally and "most of the tests didn't pass"?
All checks do pass on `master` branch, and the 3 tests that failed seem to be connected to the change in this PR.

**Comment by Arcticae** [comment]
@jainkunal closing in favour of #1002 (cache parsing was off) - full credits to you for finding this bug 👏

**Comment by Arcticae** [comment]
@jainkunal 
Released today in:
https://github.com/foundry-rs/starknet-foundry/releases/tag/v0.9.1

**Pull request closed without merging**
