### PR TITLE
removed `target` argument in stop global cheatcodes

### PR DESCRIPTION
**Pull request by 0xGreed**
Closes #

## Introduced changes

- docs on cheatcodes usage is more accurate

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Review by franciszekjob — CHANGES_REQUESTED** [review]
Only `stop_cheat_account_contract_address_global` is left and we're good to go 👍

**Comment by 0xGreed** [comment]
I pushed another commit including the `stop_cheat_account_contract_address_global` cheatcode.
I recall there is a previous pull request that references the block number, block timestamp and caller address cheatcodes

**Review by franciszekjob — APPROVED** [review]

**Review by kkawula — APPROVED** [review]

**Comment by franciszekjob** [comment]
Thanks for fixing the docs @0xGreed 🙌

**Comment by kkawula** [comment]
@0xGreed do you have an account on https://www.onlydust.com/? It will probably be possible to award you in some way.

**Pull request merged**
