### PR TITLE
docs: update snforge version

### PR DESCRIPTION
**Pull request by TAdev0**
## Introduced changes

Updates snforge version in Getting Started of the documentation

### CODE REVIEW

**Comment by TAdev0** [comment]
hi @Arcticae  i just noticed versions where outdated in the book, pushed this pr to update it. I have no idea why tests keep failing as i'm just modifying a .md file. any idea?

**Comment by Arcticae** [comment]
@TAdev0 seems you need to set up the URL for sepolia for the tests in the env variables (in your fork). That's why they are failing
https://foundry-rs.github.io/starknet-foundry/development/environment-setup.html#environmental-variables

**Comment by TAdev0** [comment]
@Arcticae  i'm closing the issue, its not a big deal anyway ^^

I populated a .env file with :
```
SEPOLIA_RPC_URL="https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
```
also tried:
```
SEPOLIA_RPC_URL=https://starknet-sepolia.public.blastapi.io/rpc/v0_7
```
and with a nethermind public endpoint as well.

I still have failing tests locally (4), dont know what the issue is

My errors are like
```
| error: Plugin diagnostic: Expected fork config must be of the form `url: <double quote string>, block_id: <snforge_std::BlockId>`.
|  --> [..]/src/lib.cairo[..]
|     #[fork(url: "https://lib.com")]
|  --> [..]/tests/test_fork.cairo[..]
| #[fork(url: "https://test.com")]
|       ^***********************^
| 
| error: Plugin diagnostic: Expected fork config must be of the form `url: <double quote string>, block_id: <snforge_std::BlockId>`.
|  --> [..]/tests/test_fork.cairo[..]
| #[fork(url: "https://starknet-sepolia.public.blastapi.io/rpc/v0_7", block_id: BlockId::Number(Latest))]
-       ^*****************************************************************************^

**Comment by Arcticae** [comment]
@TAdev0 we will investigate and probably update dox to make it easier for people - thanks for the interest in contribution nonetheless :)

**Pull request closed without merging**
