### PR TITLE
Migrated extensions to signals

### LINKED ISSUE #1610: MIgrate from post_syscall_hook to syscall signals.
Signals are superset of post syscall hooks. We should migrate to them and remove post_syscall hook from extension logic definiton.

### PR DESCRIPTION
**Pull request by MaksymilianDemitraszek**
Closes #1610 

## Introduced changes

- Migrated extensions to hooks

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Review by THenry14 — COMMENTED** [review]
is this reviewable? can you fix tests please?

**Comment by MaksymilianDemitraszek** [comment]
@Arcticae @THenry14 sorry 🙏 It supposed to work out of the box is i pushed it directly but it turned out signals had a bug 😅 .

**Comment by Arcticae** [comment]
@MaksymilianDemitraszek test still are failing

**Comment by MaksymilianDemitraszek** [comment]
@Arcticae This does not seem to be relevant to work done here, isn't it some problem with template or std_forge?

**Review by piotmag769 — APPROVED** [review]
What about deprecated runtime?

**Review by THenry14 — APPROVED** [review]

**Comment by MaksymilianDemitraszek** [comment]
@piotmag769 we would have to implement signals in deprecated runtime, though we have only one extension, imo this is not often touched part of the codebase. https://github.com/foundry-rs/starknet-foundry/issues/1978 Created a follow up issue, but imo it is a waste of time

**Pull request merged**
