### PR TITLE
Update docs since specifying account file path is not an option anymore

### PR DESCRIPTION
**Pull request by FredCoen**
The docs indicate that one can specify a path to the accounts file via the flag --accounts-file.

But that does not seem to work. Should i also make updates to the code anywhere? I am happy to dive into the code base and make the changes if you guide me a little. Recently my company moved to the starknet ecosystem so i am happy to contribute here!

I do think however on this issue its just an error message and the docs that seem to be needed correction.

Thanks

### CODE REVIEW

**Comment by Draggu** [comment]
Hi @FredCoen 

Thanks for your contribution! But `--account-file` flag seems to work as expected with substantial tests covering this area.

Could you provide steps to reproduce the issue you've found? It'd help us understand any potential problems better.

**Comment by FredCoen** [comment]
sure, i am using sncast  version 0.24.0

when i run the command 

`sncast --url $(SEPOLIA_RPC) account create --name $(name) --account-file account-file`

i get 
`error: unexpected argument '--account-file' found`

Also, when i run 
`sncast account create --help`

i dont get the option of "account-file"

**Comment by Draggu** [comment]
> sure, i am using sncast version 0.24.0
> 
> when i run the command
> 
> `sncast --url $(SEPOLIA_RPC) account create --name $(name) --account-file account-file`
> 
> i get `error: unexpected argument '--account-file' found`
> 
> Also, when i run `sncast account create --help`
> 
> i dont get the option of "account-file"

`--account-file` is a common flag https://foundry-rs.github.io/starknet-foundry/appendix/sncast/common.html so it should be used before subcommand (`account create` in this case)

**Comment by FredCoen** [comment]
ah ok sry thanks @Draggu

**Pull request closed without merging**
