### PR TITLE
Chore: Hoisted dependencies

### PR DESCRIPTION
**Pull request by Utilitycoder**
Closes #

## Introduced changes

- Hoisted common dependencies for efficiency
-

## Checklist

- [ ] Linked relevant issue
- [ ] Updated relevant documentation
- [ ] Added relevant tests
- [ ] Performed self-review of the code
- [ ] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Review by piotmag769 — COMMENTED** [review]
Thanks a lot! Fix the tests and we are good to go 🚀

**Comment by Utilitycoder** [comment]
What do you think is the issue with the tests @piotmag769? I am assuming nothing could go wrong with the tests since I didn't bump any dependency nor touch the actual code. 

I can't run the tests locally because of inadequate disk space. Could you take a look and recommend what needs to be fixed?

**Comment by piotmag769** [comment]
Will fix it, dw

**Comment by Utilitycoder** [comment]
Oh thanks, I appreciate that. BTW, what does DW mean? 

Meanwhile, please point me at any issues not so complicated, that you think an intermediate rust developer can handle.

**Comment by piotmag769** [comment]
DW == don't worry
You actually updated some dependencies since Cargo.lock was modified. Reverted it, should work now

**Review by piotmag769 — APPROVED** [review]

**Comment by Arcticae** [comment]
@Utilitycoder please look at issues marked with `good-first-issue` label :)

**Comment by Utilitycoder** [comment]
@Arcticae, I will do that and reach out if I need any help getting the issues sorted.

**Pull request merged**
