### PR TITLE
Add video tutorial link to docs

### PR DESCRIPTION
**Pull request by war-in**
## Introduced changes

image

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Comment by war-in** [comment]
I can also add a thumbnail. wdyt?
@piotmag769 @Arcticae 
image

**Review by piotmag769 — COMMENTED** [review]
Thumbnail would be nice. I think we may want to add this to README too

**Review by Arcticae — CHANGES_REQUESTED** [review]
Please embed the video

**Comment by war-in** [comment]
The main page looks like this now
image

**Comment by war-in** [comment]
> Please embed the video

embedding such large files is not possible because the file size [limit is 100MB](https://arc.net/l/quote/xhlrfbtl)

**Comment by war-in** [comment]
image

**Comment by piotmag769** [comment]
Do we plan to add it to README? @war-in  @Arcticae

**Comment by war-in** [comment]
>Do we plan to add it to README? @war-in @Arcticae

we can't embed the video like here but we can put the thumbnail which will redirect to the video

**Pull request merged**
