### PR TITLE
rand_num_cheatcode

### LINKED ISSUE #2353: Random number generation cheatcode
### Which component is your feature related to?

Forge

### Feature Request

I'd like a way to generate (pseudo) random number 

Task: Introduce a new cheatcode that will generate a random felt252. Follow the current implementation of other cheatcodes.

### PR DESCRIPTION
**Pull request by Oshioke-Salaki**
Closes #2353

## Introduced changes

Implemented a new cheatcode to generate a random number
-

## Checklist

- [x] Linked relevant issue
- [ ] Updated relevant documentation
- [ ] Added relevant tests
- [ ] Performed self-review of the code
- [ ] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Comment by Draggu** [comment]
Documentation, tests, `CHANGELOG .md` update are missing, also you need to add relevant function on `snforge_std` side. Function you added should be exposed via cheatcode api (see other cheatcodes for reference) so it can be used with `cheatcode` in cairo.

**Review by cptartur — CHANGES_REQUESTED** [review]
Hey, as said by @Draggu please actually integrate the cheatcode with foundry as this is not complete in the current stage.

See: 
https://github.com/foundry-rs/starknet-foundry/tree/master/snforge_std/src/cheatcodes

and

https://github.com/foundry-rs/starknet-foundry/tree/master/crates/cheatnet/src/runtime_extensions/forge_runtime_extension/cheatcodes

**Comment by cptartur** [comment]
Hey @Oshioke-Salaki, what's the status of this?

**Comment by Oshioke-Salaki** [comment]
Gm ser. I'm still on it. But I'm having troubles integrating it into the snforge_std. Please can I have your telegram so I can message you

**Comment by cptartur** [comment]
> Gm ser. I'm still on it. But I'm having troubles integrating it into the snforge_std. Please can I have your telegram so I can message you

You can ask in the Starknet Foundry tg group https://t.me/starknet_foundry

Please note this contribution can only be accepted once it integrates with other cheatcodes and in snforge_std

**Comment by cptartur** [comment]
Closing due to lack of activity

**Pull request closed without merging**
