### PR TITLE
feat: add auto-generation of account names for create command

### LINKED ISSUE #2709: Generate default name while using `account create`
### Which component is your feature related to?

Cast

### Feature Request

In scope of this issue we should generate default account name when `--name` flag is not passed.
For example such command
```
sncast account create --url http://127.0.0.1:5055
```

should result in successful account creation.

It should use [same logic](https://github.com/foundry-rs/starknet-foundry/blob/ed614495ec404f9003e4325009cdd9ca08d13157/crates/sncast/src/starknet_commands/account/import.rs#L203) as `account import` when `--name` is not provided.

### PR DESCRIPTION
**Pull request by petersdt**
# Generate default name while using `account create`

Closes #2709

## Introduced changes

Makes `--name` flag optional for `account create` command, matching behavior of `account import`.
When name is not provided, automatically generates incremental names (account-1, account-2, etc.).
Improves UX by reducing required flags while maintaining backwards compatibility.

## Checklist

- [x] Linked relevant issue
- [ ] Updated relevant documentation
- [ ] Added relevant tests
- [x] Performed self-review of the code
- [ ] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Review by kkawula — CHANGES_REQUESTED** [review]
I think that user should be informed what the auto-generated name is

**Review by kkawula — COMMENTED** [review]
Please add proper test, to verify it works

**Comment by franciszekjob** [comment]
Hi @petersdt, how's the progress?

**Comment by franciszekjob** [comment]
@petersdt are you still working on this?

**Comment by petersdt** [comment]
> @petersdt are you still working on this?

yes pls be done soon

**Comment by franciszekjob** [comment]
Hello @petersdt , is there any update for this?

**Comment by franciszekjob** [comment]
Closing PR due to inactivity.

**Pull request closed without merging**
