### PR TITLE
Check if lib target is selected in deployment scripts

### PR DESCRIPTION
**Pull request by abulenok**
Closes #

## Introduced changes

-

## Checklist

- [ ] Linked relevant issue
- [ ] Updated relevant documentation
- [ ] Added relevant tests
- [ ] Performed self-review of the code
- [ ] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Comment by piotmag769** [comment]
Do we plan to do that? I think it's worth adding it @THenry14

**Comment by THenry14** [comment]
> Do we plan to do that? I think it's worth adding it @THenry14

No, we don't really need this https://github.com/foundry-rs/starknet-foundry/blob/master/crates/sncast/src/starknet_commands/script.rs#L390

**Comment by piotmag769** [comment]
@THenry14 we can close it then, right?

**Comment by piotmag769** [comment]
@THenry14 imo it's still relevant, the function you linked just loads the compiled code, it doesn't solve the issue with no `[lib]` target being present in `Scarb.toml`. E.g. with `sncast` from main branch when I don't specify the lib target I get:
image

**Comment by THenry14** [comment]
> @THenry14 imo it's still relevant, the function you linked just loads the compiled code, it doesn't solve the issue with no `[lib]` target being present in `Scarb.toml`. E.g. with `sncast` from main branch when I don't specify the lib target I get: image

will look into this

**Pull request closed without merging**
