### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Etimfon007**
Prior to an issue assigned to me to consistently apply capital letters to headers, I have maintained a capitalization in the section of this particular section of the docs.

Closes #

## Introduced changes

-
-

## Checklist

- [ ] Linked relevant issue
- [ ] Updated relevant documentation
- [ ] Added relevant tests
- [ ] Performed self-review of the code
- [ ] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Comment by war-in** [comment]
Hi, thanks for contributing 🔥 It would be nice if you merge all PRs in one since they fix similar things. Thanks!

**Comment by Etimfon007** [comment]
Alright. I'll do that soon. @war-in

**Comment by cptartur** [comment]
> Alright. I'll do that soon. @war-in

Hey @Etimfon007, what's the status on combining #979 #980 #981 and #983? We'd prefer for these to be resolved as a single PR.

**Comment by Etimfon007** [comment]
That's not all though. I'll need to re-check for other inconsistencies so I can merge all at once. 

I got this(⁠•⁠‿⁠•⁠)

**Comment by Etimfon007** [comment]
Hello @cptartur , I tried merging all issues which I created into one but unfortunately, I can't merge this PR to be one with the rest without the Pull request being accepted.

**Comment by cptartur** [comment]
> Hello @cptartur , I tried merging all issues which I created into one but unfortunately, I can't merge this PR to be one with the rest without the Pull request being accepted.

You'll have to manually combine these commits into a single PR (preferably this one) either from the git cli or some other app. Unfortunately, we cannot accept a contribution in this form.

**Comment by Etimfon007** [comment]
> > Hello @cptartur , I tried merging all issues which I created into one but unfortunately, I can't merge this PR to be one with the rest without the Pull request being accepted.
> 
> You'll have to manually combine these commits into a single PR (preferably this one) either from the git cli or some other app. Unfortunately, we cannot accept a contribution in this form.

Alright. I'll manually combine them. Thanks for the feedback (⁠•⁠‿⁠•⁠)

**Pull request closed without merging**
