### PR TITLE
Add doc strings to snforge init template

### PR DESCRIPTION
**Pull request by maciektr**
I am open to any changes.

### CODE REVIEW

**Review by cptartur — COMMENTED** [review]
I think maybe it'd make sense to add a comment to the template saying something like "use this command to generate documentation"

**Comment by maciektr** [comment]
@cptartur In the code? Seems a bit excessive, we don't really have comments instructing to run `scarb build` or `snforge test` either.

**Comment by cptartur** [comment]
> @cptartur In the code? Seems a bit excessive, we don't really have comments instructing to run `scarb build` or `snforge test` either.

Right, but maybe a comment like that would improve the discoverability of scarb doc? Alternatively this could be mentioned somewhere else, maybe we should generate a `README.md` file with some commands?

**Comment by maciektr** [comment]
@cptartur 
> maybe a comment like that would improve the discoverability of scarb doc

I am a bit afraid this is a rabbit hole 😓 
We have a lot of cool futures, why not promote them all?

**Comment by cptartur** [comment]
> @cptartur
> 
> > maybe a comment like that would improve the discoverability of scarb doc
> 
> I am a bit afraid this is a rabbit hole 😓 We have a lot of cool futures, why not promote them all?

I guess we can think about promoting them better if/when we implement forge cheatsheet. Good to merge for now.

**Review by cptartur — APPROVED** [review]

**Pull request merged**
