### PR TITLE
propose verification spec changes

### PR DESCRIPTION
**Pull request by rjnrohit**
## Introduced changes

This PR introduces changes to verification proposal document mainly as follows:
1. Actual verification to be performed on class level
2. Keep `contract_address` (user should be able to provide contract_address, which we resolve to `class_hash`)
Add `class_hash`
** Either contract_address or class_hash should be provided by user
3. Change `contract_name` to `class_name` OR keep `contract_name`

## Checklist

- [ ] Linked relevant issue
- [x] Updated relevant documentation
- [ ] Added relevant tests
- [x] Performed self-review of the code
- [ ] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Comment by Arcticae** [comment]
@rjnrohit I am lacking some rationale for those changes here. They make sense on a technical level but i don't understand why we need them, could you provide some details?

**Comment by rjnrohit** [comment]
> @rjnrohit I am lacking some rationale for those changes here. They make sense on a technical level but i don't understand why we need them, could you provide some details?

Sure!
Since, Verification status labelled on class hash not on the contract addresses. And also ,If contract has been declared, it can be verified using class hash. 
Renaming of `contract-name` to `class-name` has been done because technically it is more aligned term, as requested by the voyager team

**Comment by Arcticae** [comment]
@rjnrohit i asked for folks from Walnut to review this to make sure we're on the same page with this change, since it's your common interface and i would really like it to be aligned.

**Comment by barabanovro** [comment]
We agree and all points seem reasonable. Please ping us when you have the PR with the changes so we can also implement changes on `WalnutVerificationInterface` and our backend. Thanks!

**Review by Arcticae — APPROVED** [review]

**Pull request merged**
