### PR TITLE
Add edition entry in each `Scarb.toml`

### LINKED ISSUE #2632: Add missing `edition` field to Scarb packages in the repository
In the upcoming Scarb 2.9.0, a warning will be thrown in case of package without defined `edition` field.

Set it so that using packages from our repo (like `snforge_std`) doesn't cause these warnings for the users.

### PR DESCRIPTION
**Pull request by kkawula**
Closes #2632

## Introduced changes

-

## Checklist

- [x] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

### CODE REVIEW

**Comment by kkawula** [comment]
Tried to add the latest version possible.

**Review by franciszekjob — COMMENTED** [review]
What if for some reason someone adds a package which doesn't have `edition` entry in its `Scarb.toml`? I believe we will not notice it. I think we should add test to check if every `Scarb.toml` has `edition` entry.

See [this CI step](https://github.com/foundry-rs/starknet-foundry/blob/41dd99ef9dee9fa8767760d4b9bb3c87ed5c7c46/.github/workflows/ci.yml#L228) which searches for all packages and check their formatting. We could add a similar one (display content of file and capture edition) - its shouldn't be a big effort.

**Comment by cptartur** [comment]
> What if for some reason someone adds a package which doesn't have `edition` entry in its `Scarb.toml`? I believe we will not notice it. I think we should add test which would check this.
> 
> See [this CI step](https://github.com/foundry-rs/starknet-foundry/blob/41dd99ef9dee9fa8767760d4b9bb3c87ed5c7c46/.github/workflows/ci.yml#L228) which searches for all packages and check their formatting. We could add a similar one (display content of `Scarb.toml` and capture `edition` entry) - its shouldn't be a big effort.

Scarb 2.9.0 will emit a warning. Once we have tests running on different versions of Scarb, this could be testable without writing a script.

I'd create an issue and postpone resolving that until that is resolved.

**Review by cptartur — APPROVED** [review]
Let's create a follow-up issue to migrate them all to 2024_07.

**Pull request merged**
